services:
  innova.listener.directory_tool:
    class: Innova\DirectoryBundle\Listener\ToolListener
    calls:
      - [setContainer, ["@service_container"]]
    tags:
      - { name: kernel.event_listener, event: open_tool_workspace_innova_directory, method: onWorkspaceOpen }
      - { name: kernel.event_listener, event: open_tool_desktop_innova_directory, method: onDesktopOpen }
